[package]
name = "stoplight-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
nats = { version = "0.24.0", features = ["unstable"] }
rppal = "0.15.0"
serde = "1.0.190"
serde_json = "1.0.108"
thiserror = "1.0.50"
tracing = "0.1.40"
tracing-subscriber = "0.3.17"
